name: Deploying To Lightsail
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    name: deploy-lightsail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: gradle wrapper 유효성 검증
        uses: gradle/wrapper-validation-action@v1
      - name: 스프링 부트 프로젝트 jar 빌드
        run: ./gradlew bootJar
      - name: Lightsail 인스턴스에 jar 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          rm: true
          source: "server.jar"
          target: "app/"
      - name: Lightsail 인스턴스에 서버 실행
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY}}
          script: |
            export MYSQL_URL=${{ secrets.MYSQL_URL }}
            export MYSQL_USERNAME=${{ secrets.MYSQL_URL }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            pkill java
            nohup java -jar app/server.jar 1>log/server.log 2>&1 &